### ISSUE TITLE
Reproduction Issue

### ISSUE THREAD

**Issue by dayuyang1999** [littlewine/ZeCo2#1]
Dear Authors,

thank you for your nice work and providing the code repository.

Can you please provide more detail on how to reproduce your results?
- can you please provide the checkpoint of the `colBERT` you used in your paper? becasue ColBERT did not have official released checkpoint. If you train your own checkpoint, could you provide a url toward the checkpoint?
- can you please provide the bash file you used for creating ColBERT FAISS index? I guess parameters to be used for indexing can influence search performance.
- and could you please also include some details about how you create indeces? 

Thank you,
Dayu

**Comment by littlewine** [comment]
Hi Dayu, 

I emailed you the link to the checkpoint I used, since I don't have a good storage place rn. 
I can't recall the exact parameters I used for creating the FAISS index, I can check for any logs tonight/tomorrow, but no promises there..
My best guess is that I used what's described [here](https://github.com/stanford-futuredata/ColBERT/tree/efaabb0f8731c7d96a9fe109a125357a9232f7a7#indexing)

PS: In case you are simply looking to compare/do analysis with ZeCo2 rankings and don't need a full reproduction, you can simply download the rankings provided in `data/rankings/`

**Comment by littlewine** [comment]
I also just uploaded the checkpoint at HF modelhub:
https://huggingface.co/uva-irlab/ZeCo2
